spring.application.name=PSPCrypto

spring.datasource.url=jdbc:postgresql://localhost:5432/pspCrypto_app
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql = true


spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false


spring.datasource.hikari.minimumIdle=5

spring.datasource.hikari.maximumPoolSize=20

spring.datasource.hikari.idleTimeout=30000
spring.datasource.hikari.poolName=SpringBootJPAHikariCP

spring.datasource.hikari.maxLifetime=2000000

spring.datasource.hikari.connectionTimeout=30000

logging.level.org.hibernate.SQL=DEBUG
logging.level.com.zaxxer.hikari.HikariConfig=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port = 8445

server.ssl.enabled=true
server.ssl.key-store=classpath:keystore/paymentServiceProviderBe.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=paymentServiceProvider-cert
server.ssl.client-auth=none
server.ssl.enabled-protocols=TLSv1.3

spring.config.import=optional:classpath:secrets.properties

# Crypto PSP Configuration
psp.core.api.url=https://localhost:8442
psp.name=Crypto Payment Gateway
psp.code=CRYPTO_BTC

# Bitcoin API Configuration
bitcoin.api.url=https://api.blockcypher.com/v1/btc/test3
blockstream.api.url=https://blockstream.info/testnet/api
