master-key=H6pZk8Zx5zR3y2PqN0mX9YwKc7VJmT4FQdA1B8eS2uM=

merchant-id=eb518627-5805-402e-b213-12a3da31997e
merchant-password=85d8b745-fde8-4ff2-acb9-46a91adc388b

merchant-base-url=https://localhost:8442
merchant-handshake-endpoint=/api/merchants/handshake

spring.datasource.username=postgres
spring.datasource.password=super

server.ssl.key-store-password=SertifikatZaSEP2025!