master-key=H6pZk8Zx5zR3y2PqN0mX9YwKc7VJmT4FQdA1B8eS2uM=
merchant-service-url=https://localhost:8442

# New GUID Credentials
my-app-merchant-id=f4b6b23a-b62d-4e48-9e97-9a415dc3c727
my-app-merchant-password=10929fce-dd4c-4365-9b25-bafbab1a53f3