master-key=H6pZk8Zx5zR3y2PqN0mX9YwKc7VJmT4FQdA1B8eS2uM=

server.ssl.key-store-password=SertifikatZaSEP2025!

spring.datasource.username=postgres

spring.datasource.password=super

psp.core.api.url=https://localhost:8442

psp.core.connect.endpoint=/api/payment-methods/connect

exchange.rate.api.url= http://v6.exchangerate-api.com/v6/7890a0954404ce6ea87aafbd/pair/